services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped

    ports:
      - "8090:80"
      - "81:81"
      - "8443:443"

    volumes:
      - /opt/homelab/data/npm/data:/data
      - /opt/homelab/data/npm/letsencrypt:/etc/letsencrypt

    networks:
      - proxy

networks:
  proxy:
    external: true
