services:
  n8n:
    image: n8nio/n8n:1.20.0
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - /opt/homelab/data/n8n:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=Asia/Jakarta
      - TZ=Asia/Jakarta
