services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped

    network_mode: host

    volumes:
      - /opt/homelab/compose/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /opt/homelab/data/prometheus:/prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped

    network_mode: host
