services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped

    ports:
      - "3100:3000"

    volumes:
      - /opt/homelab/data/grafana:/var/lib/grafana

    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

    networks:
      - monitoring

networks:
  monitoring:
    external: true
